[package]
name = "flate-test"
version = "0.1.0"
authors = ["tilpner <till@hoeppner.ws>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = { version = "1.0.11", features = [ "rust_backend" ] }
